# Generated by Django 4.1.7 on 2023-05-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('data', models.BinaryField(verbose_name='File')),
                ('score', models.FloatField(verbose_name='Score')),
                ('genres', models.TextField(verbose_name='Genres')),
            ],
        ),
    ]
