# Generated by Django 4.1.7 on 2023-05-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='type',
            field=models.CharField(default='', max_length=50, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
