# Generated by Django 4.1.7 on 2023-05-03 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0002_torrent_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torrent',
            options={'verbose_name': 'Торрент', 'verbose_name_plural': 'Торренты'},
        ),
    ]
