# Generated by Django 4.1.7 on 2023-05-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0003_alter_torrent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='data',
            field=models.FileField(upload_to='', verbose_name='File'),
        ),
    ]
