# Generated by Django 4.1.7 on 2023-05-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0004_alter_torrent_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torrent',
            old_name='data',
            new_name='file',
        ),
    ]
